apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: auth-service
  
  nameSpaceSelector:
    matchNames:
      - ecommerce
  
  endpoints:
    - port: http
      path: /metrics
      interval: 15s