services:
  auth-db:
    image: mysql:8.0
    container_name: auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
  
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_USER=${AUTH_DB_USER}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - DB_NAME=${AUTH_DB_NAME}
      - SECRET_KEY=${AUTH_SECRET_KEY}
      - ALGORITHM=${AUTH_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"
    depends_on:
      - auth-db

volumes:
  auth-db-data: