apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db
  namespace: ecommerce

spec:
  serviceName: order-db
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  
  template:
    metadata:
      labels:
        app: order-db

    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: MYSQL_DATABASE

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: MYSQL_ROOT_PASSWORD
          
          volumeMounts:
            - name: order-db-storage
              mountPath: /var/lb/mysql
  
  volumeClaimTemplates:
    - metadata:
        name: order-db-storage
      
      spec:
        accessModes:
          - ReadWriteOnce
        
        resources:
          requests:
            storage: 2Gi
