apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce

spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  
  template:
    metadata:
      labels:
        app: order-service
    
    spec:
      containers:
        - name: order-service
          image: ghcr.io/slehmadi/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: order-db
            
            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: ecommerce_order
            
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: DB_USER
            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: DB_PASSWORD
            
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: SECRET_KEY
            
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: ALGORITHM
            
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
            
            - name: BACKEND_CORS_ORIGINS
              value: '["http://shop.local"]'