apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: ecommerce

type: Opaque

stringData:
  DB_USER: DB_USER
  DB_PASSWORD: DB_PASSWORD
  SECRET_KEY: SECRET_KEY
  ALGORITHM: HS256
  ACCES_TOKEN_EXPIRE_MINUTES: "30"