apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 20

      batch:
        timeout: 5s
        send_batch_size: 512
        send_batch_max_size: 1024

      resource:
        attributes:
          - key: deployment.environment
            value: development
            action: upsert
          
          - key: k8s.cluster.name
            value: minikube
            action: upsert
          
          - key: project
            value: ecommerce-demo
            action: upsert
    
    extensions:
      health_check:
      zpages:

    exporters:
      debug:
        verbosity: detailed
      
      otlp_grpc/tempo:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      
      datadog:
        api:
          site: ap1.datadoghq.com
          key: ${env:DD_API_KEY}
      
      otlp_http/dynatrace:
        endpoint: ${env:DT_ENDPOINT}
        headers:
          Authorization: Api-Token ${env:DT_OTLP_API_KEY}
    
    service:
      extensions:
        - health_check
        - zpages
        
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
            - resource
          exporters:
            - debug
            - otlp_grpc/tempo
            - datadog
            - otlp_http/dynatrace
        
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
            - resource
          exporters:
            - otlp_http/dynatrace
        
        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
            - resource
          exporters:
            - otlp_http/dynatrace