apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring

spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  
  template:
    metadata:
      labels:
        app: otel-collector
    
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args:
            - "--config=/etc/otel/collector.yaml"
          
          ports:
          - containerPort: 4317
          - containerPort: 4318
          - containerPort: 13133
          - containerPort: 55679

          volumeMounts:
          - name: collector-config
            mountPath: /etc/otel
          
      volumes:
      - name: collector-config
        configMap:
          name: otel-collector-config    